server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mehrojbek/config-resource.git
  rabbitmq:
    port: 4672
    host: localhost
    username: guest
    password: guest